version: '3'

services:

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: ecommere
      MYSQL_USER: hiendv
      MYSQL_PASSWORD: password

  api-service:
    build:
      context: ./
      dockerfile: ./api.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1